
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  test_size: 0.2
  random_state: 42


model:
  type: "random_forest"  
  parameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42


features:
  time_features: ["hour", "day_of_week", "month"]
  lag_features: [1, 2, 3, 6, 12]
  

output:
  model_path: "models/"
  metrics_path: "reports/model_metrics.json"
  plots_path: "reports/plots/"


logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"